### ISSUE TITLE
Result.location seems incorrect

### ISSUE THREAD

**Issue by ThomasKingoTM** [StyraInc/regal#208]
Goal: 
To easily locate the correct location for an object in the AST to test the property. 

Issue: 
When producing a report, containing a violation, locations are generated using "result.location". However, these locations are not identical to the locations output by using either of the following: 
- opa parse --format json --json-include locations /path
- regal parse /path 

Thus, all tests will inevitably rely on the output of "result.location", which in essence makes the test invalid, as the assertion is taken from the output - and not the expected output. 

To reproduce the error: 
Open the file "rule_named_if_test.rego" and find the hard-coded location: "col": 16, ... "row": 4. 
Run either of the parse commands on a rego file such as "rule_named_if.rego". 
The AST output by the parser does not contain such a pair of values - (16,4) or (4,16) - anywhere.

**Comment by anderseknert** [comment]
I think I see what's the cause of confusion here 🙂 The `input` for the test is not the `rule_named_if.rego` file itself, but the AST from the mocked policy we get from the `ast.policy` call in the test:

```rego
r := rule.report with input as ast.policy(`
	allow := true if {
        input.foo
}`)
```

What this "expands" to would be a policy that looks like this:

```rego
package p


	allow := true if {
		input.foo
	}
```

In this case, the location of the `if` _is_ at column 16, row 4. The reason the column is 16 and not 15 here is due to the tab used for indentation in the test. This is only to make this a bit more readable. The "expanded" form isn't pretty, but that's not really an issue since it's not normally seen.

If you create a similar file yourself and parse it using `regal parse`, you should see the location present in the output:

```shell
regal parse p.rego
```
```json
{
  "rules": [
    {
      "head": {
        "assign": true,
        "location": {
          "col": 2,
          "file": "p.rego",
          "row": 4
        },
        "name": "allow",
        "ref": [
          {
            "type": "var",
            "value": "allow"
          }
        ],
        "value": {
          "location": {
            "col": 11,
            "file": "p.rego",
            "row": 4
          },
          "type": "boolean",
          "value": true
        }
      },
      "location": {
        "col": 2,
        "file": "p.rego",
        "row": 4
      }
    },
    {
      "head": {
        "location": {
          "col": 16,
          "file": "p.rego",
          "row": 4
        },
        "name": "if",
        "ref": [
          {
            "type": "var",
            "value": "if"
          }
        ],
        "value": {
          "type": "boolean",
          "value": true
        }
      },
      "location": {
        "col": 16,
        "file": "p.rego",
        "row": 4
      }
    }
  ]
}
```

(I removed everything but the rule heads from the above for brevity)

**Comment by ThomasKingoTM** [comment]
Right of course! The moment you commented, I realized my mistake :)

**Comment by anderseknert** [comment]
No worries! Just keep the questions coming 🙂
