### ISSUE TITLE
Rule: use-if and use-contains

### ISSUE THREAD

**Issue by tsandall** [StyraInc/regal#468]
It would be nice to have linter warnings for policies that are not using the `if` and `contains` keywords as these are planned to be required in 1.0. I looked at the docs and didn't see any rules that matched this description.

**Comment by anderseknert** [comment]
Agreed, we should have that in for the next release.

I have a local branch for `use-rego-v1` which would suggest this by proxy of the compiler (or if it is the parser, don't remember). But now that we have a capabilities feature, we could easily have both, and suggest `use-rego-v1` for the default capabilities, and `use-if` and `use-contains` whenever the `import_rego_v1` capability feature is missing (which would disable `use-rego-v1` with a notice).

**Comment by anderseknert** [comment]
A cursory look at this just now reminded me why this isn't as straightforward as it should be. Since neither `if` nor `contains` are [made available](https://github.com/open-policy-agent/opa/issues/5819) in the AST, our only way to check this is via the `text` attribute on the rule's `location`, which as expected returns the text representation of the whole rule. One would think/hope that maybe the `rule.head.location.text` would provide this, as then we could pretty much just do an `endswith` check for `if`/`contains` but given a rule head like `rule := true if {`, `rule.head.location.text` will only give us `rule := true`.

Finding an `if` or `contains` from the text of the whole rule is simple as long as we're dealing with something like  `rule := true if {`, but once we have rules like:

```rego
rule := [x |
    some x in input
    x == 2
] {
    some_conditions
}
```
It's not as simple. I guess one way to do this is to take the `count` of `rule.head.location.text` and then start the search for `if` or `contains` at that location in ``rule.location.text`. Not exactly pretty, but I think probably the best way to do it given our limitations.
