### ISSUE TITLE
False positive: style/external-reference

### ISSUE THREAD

**Issue by Od1nB** [StyraInc/regal#681]
Found a false positive for the `style/external-reference` rule, and upon help from Styra community members they also wanted me to make an issue for this.

https://play.openpolicyagent.org/p/qSkR9FEyFE

The issue happens when I had a wrapper function that declares some variables in a another function. Tried to recreate it into a smaller more comprehensible rule, but did not get it working. So pasting the actual function in use. All code in the playground link.

For this specific use case a `some unverified_header, unverified_payload` above the array declaration solved the issue.

Found the bug locally while using regal 21, but also seems to be present in the playground (not sure which version that is running)

**Comment by anderseknert** [comment]
Thanks @Od1nB 👍 I'll try to get a fix in for the next release.

**Comment by anderseknert** [comment]
Briefly looked into this now, and it's really the use of the unification operator (`=`) that's the culprit here. Unification is neat, but really hard to work with when using the AST alone. It is so because we'll need to determine whether a var is an input var or an output var, and if it's defined _anywhere else_ in the scope, and not necessarily in order.

To provide an example, this would be a valid rule:

```rego
weird if {
    x == 5
    y == 1
    
    y = 1
    x = 5
}
```
While this is a compile time error:
```rego
weird if {
    x == 5
    y == 1
    
    y := 1
    x := 5
}
```

So rather than doing `some unverified_header, unverified_payload`, I'd recommend using the assignment operator (`:=`) to avoid this.

```rego
[unverified_header, unverified_payload] = decode_jwt(jwt)
```
-> 
```rego
[unverified_header, unverified_payload] := decode_jwt(jwt)
```

That will come with the additional benefit of having strict mode flag `unverified_payload` as unused:

```
1 error occurred: policy.rego:26: rego_compile_error: assigned var unverified_payload unused
```

I'd like to one day make a larger effort to have Regal deal with unification, in whatever way that may be... and that's even one of the first issues created in #4

But that'll be something much larger, and I don't think we can do this as a bugfix. So I'll close this for now provided there's a good workaround, and we'll tackle this in #4 when we get there. Perhaps a custom (and optional) rule to avoid the unification operator altogether could be an interesting first step towards something more nuanced 🙂

Either way, thanks for reporting this! And keep filing issues when you encounter them. Much appreciated!
