### ISSUE TITLE
Inconsistencies with external-reference warning

### ISSUE THREAD

**Issue by asleire** [StyraInc/regal#719]
When linting my code I stumbled upon a case where I expected an external-reference warning, but there was none. I wrote a few test functions that I believe should trigger the warning but it doesn't

See play here: https://play.openpolicyagent.org/p/o5xBt1XUHP

`func_3` and `func_5` trigger warnings as expected, but the other funcs do not

**Comment by anderseknert** [comment]
Thanks @asleire! 

Yeah, the [implementation](https://github.com/StyraInc/regal/blob/main/bundle/regal/rules/style/external_reference.rego) of this rule is rather simplistic.. but I'm still surrpised by a few of these. We have a few rules that can't currently catch _all_ violations — typically because it's really expensive to do so in some cases — but we'll always have zero tolerance for false positives.

In this case it looks like we're already doing an expensive `walk`, so finding more external references currently not reported seems doable.

I'll take a look.

**Comment by anderseknert** [comment]
PR up to fix every issue reported other than `func_2`. I looked into that one briefly but it looks like it would require more effort than it's probably worth at this point. Might open another issue later to deal with some remaining items, but this level of coverage feels quite alright to me.
