### ISSUE TITLE
Completions: show suggestions after `in ...`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#757]
Since this is often a reference to a a multi-value rule somewhere, it would be handy to have suggestions pop up here.

<img width="201" alt="Screenshot 2024-05-27 at 21 58 23" src="https://github.com/StyraInc/regal/assets/510711/680348dc-620b-472f-be52-1f2b477f1d83">

**Comment by anderseknert** [comment]
Thinking some more about it, it's probably anywhere after `in`

**Comment by charlieegan3** [comment]
https://github.com/StyraInc/regal/pull/763/files#diff-e3e1f91079c773b014e85bdb5fd5d10592df4da03a3d9f9f480b36163ea65527R29 added a change that allows built in functions and rule refs to be suggested on any line that has whitespace at the start of the line. While this might come back to bite us, it seems to work and this issue is no longer present on main.


https://github.com/StyraInc/regal/assets/1774239/7261ccc8-c75e-47a0-b3b0-4c53936e6eaf
