### ISSUE TITLE
rule/argument-always-wildcard: End location is always the end of the line

### ISSUE THREAD

**Issue by charlieegan3** [StyraInc/regal#915]
There is this issue with the argument location:

![screenshot_2024-07-12_at_11 49 37](https://github.com/user-attachments/assets/4abf3fe8-6fff-4f79-ba0c-fed4349daca3)

I am not sure what the best fix is:

a) just highlight the arg itself is too small (we've avoided having single char items before)
b) highlighting the whole line is ambiguous
c) naming the violation title with the argument number involves changing the title of the violation to be templated...

Open to ideas, but I feel like what we have is better than a) & b) at least.

**Comment by anderseknert** [comment]
I have a fix for this on a dev branch. Was planning to hold off on it until I had “back ported” end location awareness to all existing rules, but that turned out to be a LOT of work, lol, so I can push what I have done so far tonight 😊

**Comment by anderseknert** [comment]
It’ll only highlight the wildcard btw, but it doesn’t look too bad when not at the start of line.

**Comment by charlieegan3** [comment]
👍 thanks Anders. No rush, I don't think it's a must-have for the next release but if you get something up we can get it in.

**Comment by anderseknert** [comment]
PR up in #917 ... it's very much just a start, but I think the implementation is sound... a _ton_ of work ahead needed to backport all existing rules though, so that's something we'll need to collaborate on later.

Please do try it out in your LSP client of choice for the rules backported so far, and compare against `main`. IMHO, this is a huge improvement in that context, and I'm really keen to see this for all of our rules :)

**Comment by anderseknert** [comment]
Fixed in #917 ... I think :) We can discuss later if there's a better way to highlight here than a single character, but at least it's correct, as opposed to highlighting the whole line after the arg.
