### ISSUE TITLE
"unable to match client identifier for initializing client" error for neovim

### ISSUE THREAD

**Issue by lemonshir** [StyraInc/regal#950]
Hi team, thanks a lot for your great work!

I noticed the following error when I opened the `rego` files with `neovim` via `LspLog` cmd:
```
[START][2024-07-30 16:32:55] LSP logging initiated
[ERROR][2024-07-30 16:32:55] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/shir/.data/nvim/mason/bin/regal"	"stderr"	"ERROR: unable to match client identifier for initializing client, using generic functionality: Neovim\n"
```

It seems that the `neovim` is not identified as an supported client [1], so the error is raised here[2].

Is this the expected behavior?

[1] https://github.com/StyraInc/regal/blob/main/internal/lsp/clients/clients.go#L14
[2] https://github.com/StyraInc/regal/blob/main/internal/lsp/server.go#L1395

**Comment by charlieegan3** [comment]
Hi there @lemonshir, thanks for your kind words about our project and for filing this issue.

The `ERROR` here is misleading, as nothing has gone wrong. `using generic functionality` is the operative phrase here, the server started ok and is operating as expected.

I think the correct action here is to just add `Neovim` to the list of known identifiers since [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig) is a supported client our Regal LS.
